//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsistencyManager.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPublisher")]
    public interface IPublisher {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPublisher/publishTemp")]
        void publishTemp(ConsistencyService.TemperatureInfo t);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPublisher/publishTemp")]
        System.Threading.Tasks.Task publishTempAsync(ConsistencyService.TemperatureInfo t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublisherChannel : ConsistencyManager.ServiceReference1.IPublisher, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublisherClient : System.ServiceModel.ClientBase<ConsistencyManager.ServiceReference1.IPublisher>, ConsistencyManager.ServiceReference1.IPublisher {
        
        public PublisherClient() {
        }
        
        public PublisherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublisherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublisherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublisherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void publishTemp(ConsistencyService.TemperatureInfo t) {
            base.Channel.publishTemp(t);
        }
        
        public System.Threading.Tasks.Task publishTempAsync(ConsistencyService.TemperatureInfo t) {
            return base.Channel.publishTempAsync(t);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISubscriber")]
    public interface ISubscriber {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriber/querySensor", ReplyAction="http://tempuri.org/ISubscriber/querySensorResponse")]
        ConsistencyService.TemperatureInfo querySensor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriber/querySensor", ReplyAction="http://tempuri.org/ISubscriber/querySensorResponse")]
        System.Threading.Tasks.Task<ConsistencyService.TemperatureInfo> querySensorAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubscriberChannel : ConsistencyManager.ServiceReference1.ISubscriber, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriberClient : System.ServiceModel.ClientBase<ConsistencyManager.ServiceReference1.ISubscriber>, ConsistencyManager.ServiceReference1.ISubscriber {
        
        public SubscriberClient() {
        }
        
        public SubscriberClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubscriberClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsistencyService.TemperatureInfo querySensor(int id) {
            return base.Channel.querySensor(id);
        }
        
        public System.Threading.Tasks.Task<ConsistencyService.TemperatureInfo> querySensorAsync(int id) {
            return base.Channel.querySensorAsync(id);
        }
    }
}
